"""核心常量定义

集中管理项目中的硬编码值，提高可维护性。
"""

# === 时间常量 ===
ONE_DAY_SECONDS = 86400
ONE_YEAR_SECONDS = 365 * ONE_DAY_SECONDS
SIX_MONTHS_SECONDS = 180 * ONE_DAY_SECONDS
TWO_YEARS_SECONDS = 2 * ONE_YEAR_SECONDS

# === 日期格式 ===
DATE_FORMAT = "%Y-%m-%d"
DATE_FORMAT_COMPACT = "%Y%m%d"

# === 市场代码 ===
A_SHARE_CODE_PREFIXES = ("0", "3", "6")
SHANGHAI_SUFFIX = ".SH"
SHENZHEN_SUFFIX = ".SZ"
HK_STOCK_SUFFIX = ".HK"

# === 数值常量 ===
BILLION = 1e9  # 十亿
HUNDRED_MILLION = 1e8  # 亿
US_SHARES_MULTIPLIER = 10000  # 美股股数转换因子
PERCENTAGE_MULTIPLIER = 100  # 百分比转换

# === 财务/分析阈值 ===
DEFAULT_TAX_RATE = 0.25  # 默认税率
MIN_GROWTH_RATE = -0.1  # 最小增长率
GROWTH_SEARCH_RANGE = (-0.05, 0.30)  # 增长率搜索范围
MAX_ITERATIONS = 100  # 最大迭代次数
TOLERANCE = 0.0001  # 容差
DEFAULT_YEAR_SPAN = 15  # 默认年份跨度

# === 缓存 TTL ===
DEFAULT_CACHE_TTL = ONE_DAY_SECONDS
HISTORICAL_DATA_TTL = ONE_YEAR_SECONDS
FINANCIAL_DATA_TTL = TWO_YEARS_SECONDS
